[env]
TERM = "xterm-256color"

[terminal]

[terminal.shell]
program = "zellij"

[window]
padding.x = 24
padding.y = 24
decorations = "None"
opacity = 0.80

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "Return", mods = "Shift", chars = "\u001b[13;2u" }
]
